# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ update-blog ]
  pull_request:
    branches: [ update-blog ]
  # schedule:
  # - cron: "0 2 * * 1-5"
  
jobs:
  build:
    env:
      SOURCE_DIR: ../../TIL/2018
      TARGET_DIR: ../private/out/

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: ./scripts/blog-updater

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1 # use v1 while subdirectory not supported
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm' 
        # working-directory: ./scripts/blog-updater  # subdirectory not yet supported: https://github.com/actions/setup-node/pull/299
    - name: test
      run: npm ci && npm test
    - name: process posts
      run: npm run process
    # - name: Push directory to another repository
    #   uses: cpina/github-action-push-to-another-repository@v1.3
